[package]
name = "web"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "WebAssembly client and WebRunner entrypoint"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
eframe = { workspace = true }
wasm-bindgen = { workspace = true }
wasm-bindgen-futures = { workspace = true }
web-sys = { workspace = true }
console_error_panic_hook = { workspace = true }
tracing-web = { workspace = true }

tracing = { workspace = true }
app = { workspace = true }
tracing-subscriber.workspace = true

[features]
default = ["accesskit", "persistence", "wgpu"]
accesskit = ["app/accesskit", "eframe/accesskit"]
persistence = ["app/persistence", "eframe/persistence"]
wgpu = ["app/wgpu", "eframe/wgpu"]
glow = ["app/glow", "eframe/glow"]

