[package]
name = "web"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "WebAssembly client and WebRunner entrypoint"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
eframe = { workspace = true, features = ["default_fonts", "wgpu", "persistence"] }
wasm-bindgen = { workspace = true }
wasm-bindgen-futures = { workspace = true }
web-sys = { workspace = true }
console_error_panic_hook = { workspace = true }
tracing-web = { workspace = true }

tracing = { workspace = true }
app = { workspace = true }
tracing-subscriber.workspace = true

